version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    container_name: steam_bot
    restart: always
    networks:
      - steam_network

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: steam_backend
    restart: always
    networks:
      - steam_network

networks:
  steam_network:
    driver: bridge